version: "3.9"

services:

  gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - auth-service
      - quiz-service
    networks:
      - quiz-network

  auth-service:
    build:
      context: ./services/auth-service-go
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
    networks:
      - quiz-network
    environment:
        JWT_SECRET: 282356f935fffe4c3ec36e497253bbce296df4e6a28a00ff23fc3b164dae0933
        INTERNAL_API_KEY: 78db15c171745baa4c39fac59eba4117e76b3cab5446618ca2524866ccf03ce8
        
  user-service:
    build: ./services/user-service-spring
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - quiz-network
    environment:
      JWT_SECRET: 282356f935fffe4c3ec36e497253bbce296df4e6a28a00ff23fc3b164dae0933
      INTERNAL_API_KEY: 78db15c171745baa4c39fac59eba4117e76b3cab5446618ca2524866ccf03ce8

  quiz-service:
    build:
      context: .
      dockerfile: services/quiz-service-laravel/Dockerfile.dev
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=postgres
      - DB_DATABASE=quiz
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - JWT_SECRET= 282356f935fffe4c3ec36e497253bbce296df4e6a28a00ff23fc3b164dae0933
      - INTERNAL_API_KEY= 78db15c171745baa4c39fac59eba4117e76b3cab5446618ca2524866ccf03ce8
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    networks:
      - quiz-network

  redis:
    image: redis:7
    networks:
      - quiz-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    networks:
      - quiz-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quiz
    ports:
      - "5432:5432"
    networks:
      - quiz-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  quiz-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data: