resolver 127.0.0.11 valid=30s;

server {
    listen 80;

    # bloquear endpoints internos
    location ^~ /internal/ {
        deny all;
    }

    location /auth {
        proxy_pass http://auth-service:8080;
    }

    location /users {
        proxy_pass http://user-service:8080;
        # proxy_set_header Host $host;
        # proxy_set_header Authorization $http_authorization;
    }

    # location /quizzes/ {
    #     proxy_pass http://quiz-service:8080/;
    # }

    # location /stats/ {
    #     proxy_pass http://stats-service:8080/;
    # }
}