server.port=8080
spring.application.name=user-service-spring
# spring.mvc.trailing-slash-match=true

spring.datasource.url=jdbc:postgresql://postgres:5432/user_service
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect