FROM php:8.4-fpm-alpine

RUN apk update && apk upgrade

RUN apk add --no-cache \
    git \
    unzip \
    curl \
    libpq-dev \
    postgresql-client \
    libzip-dev \
    libpng-dev \
    freetype-dev \
    libjpeg-turbo-dev \
    oniguruma-dev

RUN docker-php-ext-install \
    pdo \
    pdo_pgsql \
    mbstring \
    bcmath \
    pcntl \
    gd \
    zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY infrastructure/docker/php/php.ini /usr/local/etc/php/php.ini

ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /var/www

COPY infrastructure/scripts/laravel/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

# RUN addgroup -g 1000 laravel \
#  && adduser -D -u 1000 -G laravel laravel

# USER laravel

ENTRYPOINT ["entrypoint.sh"]